cache: bundler
language: ruby
sudo: false
notifications:
  email: false

rvm:
  - 2.2.5

jdk:
- oraclejdk8

cache:
  directories:
  - /tmp/solr-6.1.0

before_script:
  - cp config/database.yml.tmpl config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake ci